In [1]:
import pandas as pd
import numpy as np

print("MULTILINGUAL SOCIAL MEDIA POSTS REVIEW")

MULTILINGUAL SOCIAL MEDIA POSTS REVIEW

In [2]:
import pandas as pd
import numpy as np
import os

print("Dataset Collection Phase Started")
print("Current Working Directory:", os.getcwd())

Dataset Collection Phase Started
Current Working Directory: x:\Multilingual-Social-Media-Sentiment\notebooks

In [3]:
import os

project_root = os.path.abspath("..")

print("Project Root:")
print(project_root)

print("\nFiles:")
print(os.listdir(project_root))

Project Root:
x:\Multilingual-Social-Media-Sentiment

Files:
['.gitignore', 'app.py', 'data', 'models', 'notebooks', 'outputs', 'README.md', 'requirements.txt', 'src']

In [4]:
import pandas as pd

columns = [
    "target",
    "id",
    "date",
    "flag",
    "user",
    "text"
]

df = pd.read_csv(
    "../data/raw/english/english_sentiment140.csv",
    encoding="latin-1",
    names=columns
)

print("Shape:", df.shape)
print("\nColumns:")
print(df.columns)

print("\nTarget Counts:")
print(df["target"].value_counts())

df.head()

Shape: (1600000, 6)

Columns:
Index(['target', 'id', 'date', 'flag', 'user', 'text'], dtype='object')

Target Counts:
target
0    800000
4    800000
Name: count, dtype: int64

,target,id,date,flag,user,text
0,0,1467810369,Mon Apr 06 22:19:45 PDT 2009,NO_QUERY,_TheSpecialOne_,"@switchfoot http://twitpic.com/2y1zl - Awww, t..."
1,0,1467810672,Mon Apr 06 22:19:49 PDT 2009,NO_QUERY,scotthamilton,is upset that he can't update his Facebook by ...
2,0,1467810917,Mon Apr 06 22:19:53 PDT 2009,NO_QUERY,mattycus,@Kenichan I dived many times for the ball. Man...
3,0,1467811184,Mon Apr 06 22:19:57 PDT 2009,NO_QUERY,ElleCTF,my whole body feels itchy and like its on fire
4,0,1467811193,Mon Apr 06 22:19:57 PDT 2009,NO_QUERY,Karoli,"@nationwideclass no, it's not behaving at all...."

In [5]:
# ======================================
# ENGLISH DATASET STANDARDIZATION
# ======================================

# Keep only required columns

english_df = df[["text", "target"]].copy()

# Convert labels

english_df["sentiment"] = english_df["target"].map({
    0: "Negative",
    4: "Positive"
})

# Add language column

english_df["language"] = "English"

# Keep final columns

english_df = english_df[
    ["text", "sentiment", "language"]
]

print(english_df.shape)

english_df.head()

(1600000, 3)

                                                text sentiment language
0  @switchfoot http://twitpic.com/2y1zl - Awww, t...  Negative  English
1  is upset that he can't update his Facebook by ...  Negative  English
2  @Kenichan I dived many times for the ball. Man...  Negative  English
3    my whole body feels itchy and like its on fire   Negative  English
4  @nationwideclass no, it's not behaving at all....  Negative  English

In [6]:
english_df.to_csv(
    "../data/processed/english_processed.csv",
    index=False
)

In [7]:
english_df["sentiment"].value_counts()

sentiment
Negative    800000
Positive    800000
Name: count, dtype: int64

In [9]:
import os

folder = "../data/raw/tamil"

print(os.listdir(folder))

['tanglish_sentiment.csv']

In [10]:
import os

path = "../data/raw/tamil/tanglish_sentiment.csv"

print("Exists:", os.path.exists(path))
print("Is File:", os.path.isfile(path))
print("Is Directory:", os.path.isdir(path))

Exists: True
Is File: False
Is Directory: True

In [11]:
import pandas as pd

tamil_df = pd.read_csv(
    "../data/raw/tamil/tanglish_sentiment.csv/train.tsv",
    sep="\t"
)

print(tamil_df.shape)
print(tamil_df.columns)

tamil_df.head()

(11335, 2)
Index(['text', 'category'], dtype='object')

                                                text   category
0           Trailer late ah parthavanga like podunga  Positive
1         Move pathutu vanthu trailer pakurvnga yaru  Positive
2           Puthupetai dhanush  ah yarellam pathinga  Positive
3   Dhanush oda character ,puthu sa erukay , mass ta  Positive
4   vera level ippa pesungada mokka nu thalaivaaaaaa  Positive

In [12]:
print(tamil_df.shape)
print(tamil_df.columns)
tamil_df.head()

(11335, 2)
Index(['text', 'category'], dtype='object')

                                                text   category
0           Trailer late ah parthavanga like podunga  Positive
1         Move pathutu vanthu trailer pakurvnga yaru  Positive
2           Puthupetai dhanush  ah yarellam pathinga  Positive
3   Dhanush oda character ,puthu sa erukay , mass ta  Positive
4   vera level ippa pesungada mokka nu thalaivaaaaaa  Positive

In [13]:
tamil_df["category"].value_counts()

category
Positive           7627
Negative           1448
Mixed_feelings     1283
unknown_state       609
not-Tamil           368
Name: count, dtype: int64

In [14]:
# Keep only Positive and Negative

tamil_processed = tamil_df[
    tamil_df["category"].isin(["Positive", "Negative"])
].copy()

# Rename columns

tamil_processed = tamil_processed.rename(
    columns={
        "category": "sentiment"
    }
)

# Add language

tamil_processed["language"] = "Tamil"

# Final schema

tamil_processed = tamil_processed[
    ["text", "sentiment", "language"]
]

print(tamil_processed.shape)

tamil_processed["sentiment"].value_counts()

tamil_processed.head()

(0, 3)

Empty DataFrame
Columns: [text, sentiment, language]
Index: []

In [16]:
tamil_df["category"].unique()

array(['Positive ', 'Negative ', 'Mixed_feelings ', 'unknown_state ',
       'not-Tamil '], dtype=object)

In [17]:
print(tamil_df["category"].value_counts())

category
Positive           7627
Negative           1448
Mixed_feelings     1283
unknown_state       609
not-Tamil           368
Name: count, dtype: int64

In [18]:
tamil_df["category"] = tamil_df["category"].str.strip()

In [19]:
print(tamil_df["category"].unique())

['Positive' 'Negative' 'Mixed_feelings' 'unknown_state' 'not-Tamil']

In [20]:
# Keep only Positive and Negative

tamil_processed = tamil_df[
    tamil_df["category"].isin(["Positive", "Negative"])
].copy()

# Rename columns

tamil_processed = tamil_processed.rename(
    columns={
        "category": "sentiment"
    }
)

# Add language

tamil_processed["language"] = "Tamil"

# Final schema

tamil_processed = tamil_processed[
    ["text", "sentiment", "language"]
]

print(tamil_processed.shape)

tamil_processed["sentiment"].value_counts()

tamil_processed.head()

(9075, 3)

                                                text sentiment language
0           Trailer late ah parthavanga like podunga  Positive    Tamil
1         Move pathutu vanthu trailer pakurvnga yaru  Positive    Tamil
2           Puthupetai dhanush  ah yarellam pathinga  Positive    Tamil
3   Dhanush oda character ,puthu sa erukay , mass ta  Positive    Tamil
4   vera level ippa pesungada mokka nu thalaivaaaaaa  Positive    Tamil

In [21]:
tamil_processed.to_csv(
    "../data/processed/tamil_processed.csv",
    index=False
)

In [23]:
hindi_df = pd.read_csv("../data/raw/hindi/hindi_sentiment_analysis_dedup.csv")

print(hindi_df.shape)
print(hindi_df.columns)

hindi_df.head()

(2500, 2)
Index(['sentence', 'sentiment'], dtype='object')

                              sentence sentiment
0           आज का मौसम बहुत सुहाना है।  positive
1  मुझे यह खाना बिल्कुल पसंद नहीं आया।  negative
2     मेरा इस विषय पर कोई राय नहीं है।   neutral
3      आपकी मदद के लिए दिल से धन्यवाद।  positive
4         यह अनुभव बेहद निराशाजनक रहा।  negative

In [24]:
print(hindi_df["sentiment"].value_counts())

sentiment
positive    955
negative    848
neutral     697
Name: count, dtype: int64

In [25]:
# Keep only Positive and Negative

hindi_processed = hindi_df[
    hindi_df["sentiment"].isin(["positive", "negative"])
].copy()

# Rename column

hindi_processed = hindi_processed.rename(
    columns={
        "sentence": "text"
    }
)

# Capitalize labels

hindi_processed["sentiment"] = (
    hindi_processed["sentiment"]
    .str.capitalize()
)

# Add language column

hindi_processed["language"] = "Hindi"

# Final schema

hindi_processed = hindi_processed[
    ["text", "sentiment", "language"]
]

print(hindi_processed.shape)

print(
    hindi_processed["sentiment"].value_counts()
)

hindi_processed.head()

(1803, 3)
sentiment
Positive    955
Negative    848
Name: count, dtype: int64

                                  text sentiment language
0           आज का मौसम बहुत सुहाना है।  Positive    Hindi
1  मुझे यह खाना बिल्कुल पसंद नहीं आया।  Negative    Hindi
3      आपकी मदद के लिए दिल से धन्यवाद।  Positive    Hindi
4         यह अनुभव बेहद निराशाजनक रहा।  Negative    Hindi
6  आपका व्यवहार सच में प्रेरणादायक है।  Positive    Hindi

In [26]:
hindi_processed.to_csv(
    "../data/processed/hindi_processed.csv",
    index=False
)

In [27]:
import os

print(os.listdir("../data/processed"))

['english_processed.csv', 'hindi_processed.csv', 'tamil_processed.csv']