In [1]:
import pandas as pd
import numpy as np
import os

print("Dataset Merging Phase Started")

Dataset Merging Phase Started

In [2]:
english_df = pd.read_csv("../data/processed/english_processed.csv")
tamil_df = pd.read_csv("../data/processed/tamil_processed.csv")
hindi_df = pd.read_csv("../data/processed/hindi_processed.csv")

print("English:", english_df.shape)
print("Tamil:", tamil_df.shape)
print("Hindi:", hindi_df.shape)

English: (1600000, 3)
Tamil: (9075, 3)
Hindi: (1803, 3)

In [3]:
print(english_df.columns)
print(tamil_df.columns)
print(hindi_df.columns)

Index(['text', 'sentiment', 'language'], dtype='object')
Index(['text', 'sentiment', 'language'], dtype='object')
Index(['text', 'sentiment', 'language'], dtype='object')

In [4]:
language_summary = pd.DataFrame({
    "Language": ["English", "Tamil", "Hindi"],
    "Rows": [
        len(english_df),
        len(tamil_df),
        len(hindi_df)
    ]
})

language_summary

  Language     Rows
0  English  1600000
1    Tamil     9075
2    Hindi     1803

In [5]:
english_sample = english_df.sample(
    n=20000,
    random_state=42
)

print(english_sample.shape)

(20000, 3)

In [6]:
merged_df = pd.concat(
    [
        english_sample,
        tamil_df,
        hindi_df
    ],
    ignore_index=True
)

print(merged_df.shape)

(30878, 3)

In [7]:
merged_df = merged_df.sample(
    frac=1,
    random_state=42
).reset_index(drop=True)

merged_df.head()

                                                text sentiment language
0  Next date - Birmingham, The Rainbow, Sun 7th J...  Positive  English
1   Action king dialogue semma..... avanoda sindh...  Positive    Tamil
2   Appedilaam nadekaathu, nadake kudaathu!! The ...  Positive    Tamil
3   Looks like d Mixture of  Kaala+Kabali.....   ...  Positive    Tamil
4                      Nfg greatest hits cd cracked   Negative  English

In [8]:
print(
    merged_df["language"].value_counts()
)

language
English    20000
Tamil       9075
Hindi       1803
Name: count, dtype: int64

In [9]:
print(
    merged_df["sentiment"].value_counts()
)

sentiment
Positive    18640
Negative    12238
Name: count, dtype: int64

In [10]:
merged_df.to_csv(
    "../data/processed/multilingual_sentiment.csv",
    index=False
)

print("Dataset Saved Successfully")

Dataset Saved Successfully

In [4]:
import pandas as pd

main_df = pd.read_csv("../data/processed/multilingual_sentiment.csv")
extra_df = pd.read_csv("../data/processed/tamil_negative_extra.csv")

updated_df = pd.concat([main_df, extra_df], ignore_index=True)

print("Old Shape:", main_df.shape)
print("New Shape:", updated_df.shape)

# Overwrite the original file
updated_df.to_csv(
    "../data/processed/multilingual_sentiment.csv",
    index=False
)

Old Shape: (30878, 3)
New Shape: (30928, 3)

In [5]:
import pandas as pd

df = pd.read_csv("../data/processed/multilingual_sentiment.csv")

print(df.groupby("language")["sentiment"].value_counts())

language  sentiment
English   Positive     10058
          Negative      9942
Hindi     Positive       955
          Negative       848
Tamil     Positive      7627
          Negative      1498
Name: count, dtype: int64

In [6]:
df = pd.read_csv("../data/processed/multilingual_sentiment.csv")

positive_tamil = df[
    (df["language"]=="Tamil") &
    (df["sentiment"]=="Positive")
]

print(positive_tamil.sample(20)["text"].tolist())

[' Inga Rajini ya pathi mattum comment pannunga nan Vijay sethupathika papen aniruthuka Papen apdina adichu underwearoda oda vituven....Thalaivar forever', ' 775k likes just 25k to 800k  Thala fans come on...', ' My dear Thalaaaa... Marana waiting for NKP', ' In Vetri Maaran we trust', ' Thalaivar mass vijaysethupathi sir Vera level', ' Last  dance  vera  lvl', ' Vara level thala tharika vetalam thala', ' Indha pongal nammludhu tham mmaa  Petta Parakk', ' POWER PACK ACTING AND DIALOGUE DELIVERY AND VERA LEVEL LOOK THALA....KOLA WAITING FOR NERKONDA PARVAI...MASS BGM...', ' THE KING OF TAMIL NADU THALA', ' Abiya oh thala kudava nadichurukka kadavule abi alugachi', ' suyama sindhika therinja ellaruma HERO dan', ' Thalaiva u r simply superb Indian super star', ' Never ......EVER....GIVE..up indha yaaru bike LA irrukkoo oru like poodunga', ' No 2 trading in Sri lanka', ' ino neraya neraya nerayah pah.. goosebumps theater will be shattered', " Kollywood - we don't copy Bollywood. AMITABH Bachhan -", ' My Thalapathy fan thalaivar pakkkkkkkka maaaaaassssss', ' Boos is back rajani is super', ' Sk aanna.. mass hero... am waiting']

In [2]:
import pandas as pd
main_df = pd.read_csv("../data/processed/multilingual_sentiment.csv")
positive_df = pd.read_csv("../data/processed/tamil_positive_extra.csv")

updated_df = pd.concat(
    [main_df, positive_df],
    ignore_index=True
)

updated_df.to_csv(
    "../data/processed/multilingual_sentiment.csv",
    index=False
)